{% set version = "1.40.0" %}

package:
  name: dub
  version: {{ version }}

source:
  url: https://github.com/dlang/dub/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 52b963137e8a671e48ce3b64eb1e424f6a3c137b8001cf74fb98932def61c171

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - ldc
    - dtools
    - libcurl
  run:
    - ldc
    - libcurl

test:
  commands:
    - dub --version

about:
  home: https://github.com/dlang/dub/
  license: MIT
  license_file: LICENSE
  summary: Package and build management system for D

extra:
  recipe-maintainers:
    - dpryan79
