{% set version = "1.38.1" %}

package:
  name: dub
  version: {{ version }}

source:
  url: https://github.com/dlang/dub/archive/refs/tags/v{{ version }}.tar.gz
  sha256: a7c9a2f819fdea7359f298cba76e81a24ca1536d756c3b4b98c2480463c37907

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - ldc
    - dtools
    - libcurl
  run:
    - ldc
    - libcurl

test:
  commands:
    - dub --version

about:
  home: https://github.com/dlang/dub/
  license: MIT
  license_file: LICENSE
  summary: Package and build management system for D

extra:
  recipe-maintainers:
    - dpryan79
