{% set version = "1.29.1" %}

package:
  name: dub
  version: {{ version }}

source:
  url: https://github.com/dlang/dub/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7cf67f1359ac042ed98420933408dbbbfff39d27021c086d271ee2cf6301b15c

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('c') }}
  host:
    - ldc
    - dtools
    - libcurl
  run:
    - ldc
    - libcurl

test:
  commands:
    - dub --version

about:
  home: https://github.com/dlang/dub/
  license: MIT
  license_file: LICENSE
  summary: Package and build management system for D

extra:
  recipe-maintainers:
    - dpryan79
