{% set version = "1.32.1" %}

package:
  name: dub
  version: {{ version }}

source:
  url: https://github.com/dlang/dub/archive/refs/tags/v{{ version }}.tar.gz
  sha256: cad53d96230d7bccd886c827d8b89ba136479ffa1a504ecd17f960c2ea50ee45

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('c') }}
  host:
    - ldc
    - dtools
    - libcurl
  run:
    - ldc
    - libcurl

test:
  commands:
    - dub --version

about:
  home: https://github.com/dlang/dub/
  license: MIT
  license_file: LICENSE
  summary: Package and build management system for D

extra:
  recipe-maintainers:
    - dpryan79
