{% set version = "1.31.1" %}

package:
  name: dub
  version: {{ version }}

source:
  url: https://github.com/dlang/dub/archive/refs/tags/v{{ version }}.tar.gz
  sha256: dce1b3f7d21f6b111830d849e6f417853bab66d9036df212aec237c1f724bc4f

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('c') }}
  host:
    - ldc
    - dtools
    - libcurl
  run:
    - ldc
    - libcurl

test:
  commands:
    - dub --version

about:
  home: https://github.com/dlang/dub/
  license: MIT
  license_file: LICENSE
  summary: Package and build management system for D

extra:
  recipe-maintainers:
    - dpryan79
