{% set version = "1.42.0" %}

package:
  name: dub
  version: {{ version }}

source:
  url: https://github.com/dlang/dub/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7f0a5133885a71b89f7a683d8f3e3616e070238424b36ae04fdbc0d7b99e3027

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - ldc
    - dtools
    - libcurl
  run:
    - ldc
    - libcurl

test:
  commands:
    - dub --version

about:
  home: https://github.com/dlang/dub/
  license: MIT
  license_file: LICENSE
  summary: Package and build management system for D

extra:
  recipe-maintainers:
    - dpryan79
