{% set version = "1.36.0" %}

package:
  name: dub
  version: {{ version }}

source:
  url: https://github.com/dlang/dub/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 16ac09875889af03abeeca9b60777ee51611c86b3efe5869db3331d2fd97fd2b

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('c') }}
  host:
    - ldc
    - dtools
    - libcurl
  run:
    - ldc
    - libcurl

test:
  commands:
    - dub --version

about:
  home: https://github.com/dlang/dub/
  license: MIT
  license_file: LICENSE
  summary: Package and build management system for D

extra:
  recipe-maintainers:
    - dpryan79
